### ISSUE TITLE
Infinite loop for the MelloMusicGroup script

### ISSUE THREAD

**Issue by charlescng** [phpfunk/vinylfinder#1]
There are a couple of issues with the script.

- It doesn't check the response code ($status)
- The exit condition for the while loop depends on "good" pages coming back. When there are errors, it may get stuck in an infinite loop

As of writing, there are five pages in the vinyl collection (https://www.mellomusicgroup.com/collections/vinyl?page=5). I see the script running with URLs like `/collections/vinyl?page=4808278`

**Comment by phpfunk** [comment]
Thanks Charles and sorry about that. Will get this fixed up. Unfortunately things like https://www.mellomusicgroup.com/collections/vinyl?page=345345 won't return a response code that would fail. It's still a 200.

**Comment by phpfunk** [comment]
Also Charles, is this still happening? I remember fixing this ages ago. If it doesn't find any releases on a page, it will break out of the loop. Malformed HTML, bad response, etc. Just tested it and it works as it should.

The log you referenced has happened in the past but was fixed on this commit: https://github.com/phpfunk/vinylfinder/commit/2cdec4c0381fd2d1103ac74501c1ba47ac383c18

Let me know if that log was recent or not.

<img width="352" alt="screen shot 2017-10-10 at 2 46 55 pm" src="https://user-images.githubusercontent.com/72203/31404438-1446f530-adca-11e7-9ed7-3f9c55a0c8b0.png">
